server:
  port: 8080

spring:
  application:
    name: UserManagement
  datasource:
    url: jdbc:mysql://localhost:3306/user-management?createDatabaseIfNotExist=true
    username: root
    password: Vai@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

